#theme: jekyll-theme-architect
remote_theme: chrisrhymes/bulma-clean-theme
title: SaGe
description: a Web Preempted SPARQL query engine for Knowledge Graphs
permalink: pretty

favicon: /sage_logo.png
footer_menu: home_footer

paginate: 5
paginate_path: "/blog/page:num"

