#theme: jekyll-theme-architect
remote_theme: chrisrhymes/bulma-clean-theme
title: SaGe
tagline: A Preemptive SPARQL Query Engine for Knowledge Graphs
email: sage@univ-nantes.fr
description: >
  A Preemptive SPARQL Query Engine for Knowledge Graphs
url: "https://sage-org.github.io"
permalink: pretty
favicon: /sage_logo.png
footer_menu: home_footer

paginate: 5
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
      hero_height: is-small
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "GDD Team"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      hero_height: is-small

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: gddteam
  



